name: CI Workflow
on:
  - push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: bulid
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
